#!/bin/bash

#For the first three octets, make sure you use your proper network ID. Remember from networking class: if a class C subnet is used, the host bits are
#on the last octet or decminal value. The final octet below is enumerated using brace expansion and without xargs, ths script would include a for loop. 

#Unsure of what your network ID is? Try this: 
#ip route | grep default | head -1 | awk '{ print $3 }' | sed 's/.$//'


echo 192.168.1.{1..254} | xargs -P254 -d' ' -L1 ping -c1 -w1 2>/dev/null | grep 'bytes from' | sort -V 
